// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Render_BnB_v2.Data;

#nullable disable

namespace RenderBnBv2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250615000000_AddDisplayNameToProfile")]
    partial class AddDisplayNameToProfile
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Render_BnB_v2.Models.Profile", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("BioHeadline")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("BirthDecade")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DisplayName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FavoriteSong")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FunFact")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Interest")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Job")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Languages")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LivingPlace")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Pets")
                    .HasColumnType("nvarchar(max)");

                b.Property<byte[]>("ProfilePicture")
                    .HasColumnType("varbinary(max)");

                b.Property<string>("Skill")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("TimeSpent")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("University")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("UserId").IsUnique();

                b.ToTable("Profiles");
            });
        }
    }
}
